version: '3.8'

services:
  db1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - DB-A:/var/lib/mysql
    hostname: db1

  db2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - DB-B:/var/lib/mysql
    hostname: db2

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6666:6379'
    volumes:
      - redis-data:/data
    hostname: redis

  serviceA:
    image: servicea:latest
    restart: always
    environment:
      - DB_HOST=db1
      - DB_PORT=3307
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db1
    deploy:
      replicas: 2
    ports:
      - '5000'

  serviceB:
    image: serviceb:latest
    restart: always
    environment:
      - DB_HOST=db2
      - DB_PORT=3308
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db2
      - redis
    deploy:
      replicas: 2
    ports:
      - '5000'

  gateway:
    build: ./Gateway
    restart: always
    ports:
      - '5003:5003'
    hostname: gateway

  service-discovery:
    build: ./service_discovery
    restart: always
    ports:
      - '5005:5005'
      - '50051:50051'
    hostname: service-discovery

volumes:
  DB-A:
  DB-B:
  redis-data: