version: '3.3'
services:
  db1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - DB-A:/var/lib/mysql

  db2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - DB-B:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6666:6379'
    volumes:
      - redis-data:/data

volumes:
  DB-A:
  DB-B:
  redis-data: