services:
  db1-1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - DB-A:/var/lib/mysql
    hostname: db1

  db1-2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - DB-A-1:/var/lib/mysql
    hostname: db1

  db1-3:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      ports:
        - '3310:3306'
      expose:
        - '3306'
      volumes:
        - DB-A-2:/var/lib/mysql
      hostname: db1

  db2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - DB-B:/var/lib/mysql
    hostname: db2

  db-wearhouse:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3311:3306'
    expose:
      - '3306'
    volumes:
      - DB-WEARHOUSE:/var/lib/mysql
    hostname: wearhouse

  etl-job:
    build: ./DataWearhouse
    restart: always
    depends_on:
      - db-wearhouse

  redis1:
    image: redis:latest
    restart: always
    ports:
      - '6669:6379'
    volumes:
      - redis-data:/data
    hostname: redis1

  redis2:
    image: redis:latest
    restart: always
    ports:
      - '6667:6379'
    volumes:
      - redis-data:/data
    hostname: redis2

  redis3:
    image: redis:latest
    restart: always
    ports:
      - '6668:6379'
    volumes:
      - redis-data:/data
    hostname: redis3

  servicea:
    build: ./ServiceA
    restart: always
    environment:
      - DB_HOST=db1
      - DB_PORT=3307
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db1-1
      - db1-2
      - db1-3
    deploy:
      replicas: 2
    ports:
      - '5000'

  serviceb:
    build: ./ServiceB
    restart: always
    environment:
      - DB_HOST=db2
      - DB_PORT=3308
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db2
      - redis1
      - redis2
      - redis3
      - redis-consistent-hashing
    deploy:
      replicas: 2
    ports:
      - '5000'

  database-replication:
    build: ./DatabaseReplication
    restart: always
    depends_on:
      - db1-1
      - db1-2
      - db1-3
    ports:
      - '5555:5000'
    hostname: database-replication

  gateway:
    build: ./Gateway
    restart: always
    ports:
      - '5003:5003'
    hostname: gateway

  service-discovery:
    build: ./service_discovery
    restart: always
    ports:
      - '5005:5005'
      - '50051:50051'
    hostname: service-discovery

  redis-consistent-hashing:
    build: ./RedisConsistentHashing
    restart: always
    ports:
      - '5006:5006'
    hostname: redis-consistent-hashing
    depends_on:
      - redis1
      - redis2
      - redis3

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  DB-A:
  DB-A-1:
  DB-A-2:
  DB-B:
  DB-WEARHOUSE:
  redis-data: